Bugfix: Removing unused 'ARBITRARY_SIZE'
Found error:
Traceback (most recent call last):
  File "/home/pablo/mambaforge/envs/colab_cellpose/lib/python3.10/site-packages/cellpose/export.py", line 56, in <module>
    from bioimageio.spec.model.v0_5 import (
ImportError: cannot import name 'ARBITRARY_SIZE' from 'bioimageio.spec.model.v0_5' (/home/pablo/mambaforge/envs/colab_cellpose/lib/python3.10/site-packages/bioimageio/spec/model/v0_5.py)

It turns out, they removed 'ARBITRARY_SIZE':
https://github.com/bioimage-io/spec-bioimage-io/commit/39d343681d427ec93cf69eef7597d9eb9678deb1

By removing the parameter, this code will work again.